### ISSUE TITLE
spark-logs does not exist in namenode for sandbox-zeppelin.yml

### ISSUE THREAD

**Issue by rockie-yang** [bwv988/datascience-docker-sandbox#1]
**Reproduce steps:**
- launch sandbox-zeppelin.yml with docker-composer
- attach to spark-master
- execute /opt/spark-2.0.0/bin/spark-shell 

**error:** 

```
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel).
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/spark-2.0.0/jars/slf4j-log4j12-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/hadoop-2.7.2/share/hadoop/common/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
16/10/10 07:52:30 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
16/10/10 07:53:30 ERROR spark.SparkContext: Error initializing SparkContext.
java.io.FileNotFoundException: File does not exist: hdfs://namenode:8020/spark-logs
    at org.apache.hadoop.hdfs.DistributedFileSystem$22.doCall(DistributedFileSystem.java:1309)
    at org.apache.hadoop.hdfs.DistributedFileSystem$22.doCall(DistributedFileSystem.java:1301)
    at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
    at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1317)
    at org.apache.spark.scheduler.EventLoggingListener.start(EventLoggingListener.scala:93)
    at org.apache.spark.SparkContext.<init>(SparkContext.scala:519)
    at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2256)
    at org.apache.spark.sql.SparkSession$Builder$$anonfun$8.apply(SparkSession.scala:831)
    at org.apache.spark.sql.SparkSession$Builder$$anonfun$8.apply(SparkSession.scala:823)
    at scala.Option.getOrElse(Option.scala:121)
    at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:823)
    at org.apache.spark.repl.Main$.createSparkSession(Main.scala:95)
    at $line3.$read$$iw$$iw.<init>(<console>:15)
    at $line3.$read$$iw.<init>(<console>:31)
    at $line3.$read.<init>(<console>:33)
    at $line3.$read$.<init>(<console>:37)
    at $line3.$read$.<clinit>(<console>)
    at $line3.$eval$.$print$lzycompute(<console>:7)
    at $line3.$eval$.$print(<console>:6)
    at $line3.$eval.$print(<console>)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:786)
    at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1047)
    at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:638)
    at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:637)
    at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
    at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
    at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:637)
    at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:569)
    at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:565)
    at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:807)
    at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:681)
    at scala.tools.nsc.interpreter.ILoop.processLine(ILoop.scala:395)
    at org.apache.spark.repl.SparkILoop$$anonfun$initializeSpark$1.apply$mcV$sp(SparkILoop.scala:38)
    at org.apache.spark.repl.SparkILoop$$anonfun$initializeSpark$1.apply(SparkILoop.scala:37)
    at org.apache.spark.repl.SparkILoop$$anonfun$initializeSpark$1.apply(SparkILoop.scala:37)
    at scala.tools.nsc.interpreter.IMain.beQuietDuring(IMain.scala:214)
    at org.apache.spark.repl.SparkILoop.initializeSpark(SparkILoop.scala:37)
    at org.apache.spark.repl.SparkILoop.loadFiles(SparkILoop.scala:94)
    at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:920)
    at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:909)
    at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:909)
    at scala.reflect.internal.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:97)
    at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:909)
    at org.apache.spark.repl.Main$.doMain(Main.scala:68)
    at org.apache.spark.repl.Main$.main(Main.scala:51)
    at org.apache.spark.repl.Main.main(Main.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:729)
    at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:185)
    at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:210)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:124)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
java.io.FileNotFoundException: File does not exist: hdfs://namenode:8020/spark-logs
  at org.apache.hadoop.hdfs.DistributedFileSystem$22.doCall(DistributedFileSystem.java:1309)
  at org.apache.hadoop.hdfs.DistributedFileSystem$22.doCall(DistributedFileSystem.java:1301)
  at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
  at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1317)
  at org.apache.spark.scheduler.EventLoggingListener.start(EventLoggingListener.scala:93)
  at org.apache.spark.SparkContext.<init>(SparkContext.scala:519)
  at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2256)
  at org.apache.spark.sql.SparkSession$Builder$$anonfun$8.apply(SparkSession.scala:831)
  at org.apache.spark.sql.SparkSession$Builder$$anonfun$8.apply(SparkSession.scala:823)
  at scala.Option.getOrElse(Option.scala:121)
  at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:823)
  at org.apache.spark.repl.Main$.createSparkSession(Main.scala:95)
  ... 47 elided
<console>:14: error: not found: value spark
       import spark.implicits._
              ^
<console>:14: error: not found: value spark
       import spark.sql
              ^
```

**Solution:**

create /spark-logs on namenoden before launch spark-shell

```
hadoop fs -mkdir /spark-logs
```

**Comment by bwv988** [comment]
Hi Rockie, 

thanks for the report. This is essentially timing issue.

Spark has a _service dependency_ on Hadoop namenode to be up and running.

Spark logs are created as part of the entrypoint script:

https://github.com/bwv988/docker-datascience-spark/blob/master/ds-spark-base/files/spark-entrypoint.sh

However if Spark is started before the Namenode is up, logs won't work.

In the Zeppelin container, I had implemented a somewhat hacky "service wait" script for precisely this purpose:

https://github.com/bwv988/docker-zeppelin/blob/master/files/service_wait.sh

but it's not ideal. Haven't yet found a better solution in Compose. 

Probably this issue can be solved more generically and simply in Kubernetes.

**Comment by rockie-yang** [comment]
according to the setup, there are dependencies

```
spark-master -> hive -> hadoop-namenode & hadoop-datanode1
```

so docker composer will ensure that spark-master start in the last. Then the directory creation in spark-master should be successful. 

If I run following command in spark-master

```
hadoop fs -ls /
```

There is no /spark-logs

I think the the hadoop cli configuration in spark-master in not connected to hadoop namenode.

**Comment by bwv988** [comment]
Hi Rockie, 

Docker compose does have a service startup ordering indeed, but it doesn't mean that it waits until the service becomes "ready". This is by design; read more about it here:

https://docs.docker.com/compose/startup-order/

The temporary solution solution is to add a service wait facility, as pointed out above, which is what I have done in:

https://github.com/bwv988/docker-datascience-spark

but have yet to do in:

https://github.com/bwv988/docker-spark

However, you are right in saying that the hadoop config is not connected in the spark container. This is because the environment injection script isn't launched. I just verified by running it manually.

Will get this fixed.

``` bash
[12:22:06][sral@centaurus:~]$ docker ps
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS                                                NAMES
2d9923171b78        bwv988/ds-spark-master   "/entrypoints/spark-m"   12 seconds ago      Up 11 seconds       0.0.0.0:8080->8080/tcp                               spark-master
e8af58f92566        bwv988/docker-zeppelin   "/entrypoints/zeppeli"   11 minutes ago      Up 11 minutes       0.0.0.0:9090->9090/tcp                               zeppelin
b52fcd6c16b6        bwv988/ds-spark-worker   "/entrypoints/spark-w"   11 minutes ago      Up 11 minutes                                                            dockercompose_spark-worker_1
91ff741608d4        bwv988/hadoop-hive       "/entrypoints/hive-en"   11 minutes ago      Up 11 minutes       0.0.0.0:10000->10000/tcp, 0.0.0.0:10002->10002/tcp   hive
0345a6bc5756        bwv988/hadoop-datanode   "/entrypoints/hadoop-"   11 minutes ago      Up 11 minutes                                                            datanode1
12f5b5bf9bc8        bwv988/hadoop-namenode   "/entrypoints/hadoop-"   11 minutes ago      Up 11 minutes       0.0.0.0:8020->8020/tcp, 0.0.0.0:50070->50070/tcp     namenode
26035b1e40fa        bwv988/zookeeper         "/opt/zookeeper/bin/z"   11 minutes ago      Up 11 minutes       2888/tcp, 0.0.0.0:2181->2181/tcp, 3888/tcp           zookeeper
07de8734bf5d        bwv988/postgres-hive     "/docker-entrypoint.s"   11 minutes ago      Up 11 minutes       0.0.0.0:5432->5432/tcp                               postgres
[12:23:22][sral@centaurus:~]$ docker exec -it spark-master bash
root@2d9923171b78:/workdir# hadoop fs -ls /                                                                                                                                                                                                   
Found 23 items
-rwxr-xr-x   1 root root          0 2016-10-10 11:23 /.dockerenv
drwxr-xr-x   - root root       4096 2016-09-06 20:24 /bin
drwxr-xr-x   - root root       4096 2016-05-30 04:18 /boot
drwxr-xr-x   - root root        360 2016-10-10 11:23 /dev
drwxr-xr-x   - root root       4096 2016-09-19 10:20 /entrypoints
drwxr-xr-x   - root root       4096 2016-10-10 11:23 /etc
drwxr-xr-x   - root root       4096 2016-09-06 20:30 /hadoop-data
drwxr-xr-x   - root root       4096 2016-05-30 04:18 /home
drwxr-xr-x   - root root       4096 2016-09-19 10:10 /lib
drwxr-xr-x   - root root       4096 2016-09-19 10:09 /lib64
drwxr-xr-x   - root root       4096 2016-06-08 16:28 /media
drwxr-xr-x   - root root       4096 2016-06-08 16:28 /mnt
drwxr-xr-x   - root root       4096 2016-10-10 11:23 /opt
dr-xr-xr-x   - root root          0 2016-10-10 11:23 /proc
drwx------   - root root       4096 2016-10-10 11:23 /root
drwxr-xr-x   - root root       4096 2016-06-08 16:28 /run
drwxr-xr-x   - root root       4096 2016-09-06 20:24 /sbin
drwxr-xr-x   - root root       4096 2016-06-08 16:28 /srv
dr-xr-xr-x   - root root          0 2016-10-10 11:17 /sys
drwxrwxrwt   - root root       4096 2016-10-10 11:23 /tmp
drwxr-xr-x   - root root       4096 2016-10-10 11:23 /usr
drwxr-xr-x   - root root       4096 2016-09-19 10:09 /var
drwxr-xr-x   - root root       4096 2016-09-22 12:21 /workdir
root@2d9923171b78:/workdir# bash /entrypoints/inject_
inject_hadoop_cfg.sh  inject_spark_cfg.sh   
root@2d9923171b78:/workdir# bash /entrypoints/inject_hadoop_cfg.sh 
Configuring Hadoop...
Configuring core
 - Setting hadoop.proxyuser.hue.hosts=*
 - Setting fs.defaultFS=hdfs://namenode:8020
 - Setting hadoop.proxyuser.hue.groups=*
 - Setting hadoop.http.staticuser.user=root
Configuring hdfs
 - Setting dfs.permissions.enabled=false
- Setting dfs.webhdfs.enabled=true
Configuring yarn
 - Setting yarn.resourcemanager.fs.state-store.uri=/rmstate
 - Setting yarn.timeline-service.generic-application-history.enabled=true
 - Setting yarn.resourcemanager.recovery.enabled=true
 - Setting yarn.log-aggregation-enable=true
 - Setting yarn.timeline-service.enabled=true
 - Setting yarn.resourcemanager.store.class=org.apache.hadoop.yarn.server.resourcemanager.recovery.FileSystemRMStateStore
 - Setting yarn.resourcemanager.system-metrics-publisher.enabled=true
 - Setting yarn.nodemanager.remote-app-log-dir=/app-logs
 - Setting yarn.resourcemanager.resource.tracker.address=resourcemanager:8031
 - Setting yarn.resourcemanager.hostname=resourcemanager
 - Setting yarn.timeline-service.hostname=historyserver
 - Setting yarn.log.server.url=http://historyserver:8188/applicationhistory/logs/
 - Setting yarn.resourcemanager.scheduler.address=resourcemanager:8030
 - Setting yarn.resourcemanager.address=resourcemanager:8032
Configuring httpfs
Configuring kms
Configuring for multihomed network.
root@2d9923171b78:/workdir# hadoop fs -ls /                        
Found 2 items
drwxrwxr-x   - root supergroup          0 2016-09-05 13:57 /tmp
drwxr-xr-x   - root supergroup          0 2016-09-05 17:55 /user
root@2d9923171b78:/workdir# 
```

Thanks for pointing this out!

**Comment by bwv988** [comment]
Ok I have pushed the changes to docker-spark and docker-datascience-spark. Want to give this a go and test on your side?
